// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKIyO_u2m59D1yzs9XyOVD1dLeI6fhSGg',
    appId: '1:208765013299:web:f994b1fe02a441de2ac246',
    messagingSenderId: '208765013299',
    projectId: 'fireflow-8e095',
    authDomain: 'fireflow-8e095.firebaseapp.com',
    storageBucket: 'fireflow-8e095.firebasestorage.app',
    measurementId: 'G-P2FKEY7C7L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtMwdxw7-gCNc4HRbuL0rScDLQ-sLvnrA',
    appId: '1:208765013299:android:545630815fff0eef2ac246',
    messagingSenderId: '208765013299',
    projectId: 'fireflow-8e095',
    storageBucket: 'fireflow-8e095.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_Y-TscnzXhFK6myhBbm4hqWn3T7T1tWw',
    appId: '1:208765013299:ios:b71e137aa4f8a4342ac246',
    messagingSenderId: '208765013299',
    projectId: 'fireflow-8e095',
    storageBucket: 'fireflow-8e095.firebasestorage.app',
    iosBundleId: 'com.pawelpasik.mestio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKIyO_u2m59D1yzs9XyOVD1dLeI6fhSGg',
    appId: '1:208765013299:web:e692ec738beca4ba2ac246',
    messagingSenderId: '208765013299',
    projectId: 'fireflow-8e095',
    authDomain: 'fireflow-8e095.firebaseapp.com',
    storageBucket: 'fireflow-8e095.firebasestorage.app',
    measurementId: 'G-Y5XVCF4VXY',
  );
}
